erp/urls.py
from django.contrib import admin
from django.urls import path,include
from qlns.views import *
from khovan.views import *
from khachhang.views import *
from django.conf import settings

from django.conf.urls.static import static

admin.site.index_title="Quản Trị Hệ Thống"
urlpatterns = [
    path('admin/', admin.site.urls,name="admin"),
    path('pdf/', include('mergepdf.urls')),
    path('report/',Report.as_view(),name='report'),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('', Index.as_view(),name='index'),
    path('login/', Login.as_view(),name='login'),
    path('logout',Logout.as_view(),name='logout'),
    path('api-auth/', include('rest_framework.urls')),
    path('giao-viec/', Giaoviec.as_view(),name='giaoviec'),
    path('nhanvien/', Nhanvientotal.as_view(), name='nhanvien'),
    path('get-nhan-vien/', Getnhanvien.as_view(),name='getnhanvien'),
    path('profile/',Profile.as_view(),name='profile'),
    path('dsnhanvien/',Dsnhanvien.as_view(),name='dsnhanvien'),
    path('viewnhanvien/', Viewnhanvien.as_view(), name='viewnhanvien'),
    path('deletenhanvien/',Delete_checkbox.as_view(), name='delete-nhanvien'),
    path('phieu-luong-upload/',Phieuluongupload.as_view(), name='phieuluongupload'),
    path('nhanvien/delete/<int:nhanvien_id>',Deletenhanvien.as_view(),name='deletenhanvien'),
    path('nhan-vien/xem-nhan-vien/<int:nhanvien_id>', Changenhanvien.as_view(), name='xemnhanvien'),
    path('phieu-luong/nhan-vien/<int:nhanvien_id>', Phieuluongcanhan.as_view(), name='xemphieuluong'),
    path('phieu-luong-user', Phieuluonguser.as_view(), name='xemphieuluonguser'),

    path('nhan-vien/tao-de-xuat/',Dexuats.as_view(),name='form-de-xuat'),
    path('nhan-vien/de-xuat-chua-duyet/',Dexuatchuaduyet.as_view(),name='dexuat-chua-duyet'),
    path('nhan-vien/de-xuat-da-duyet/',Dexuatdaduyet.as_view(),name='dexuat-da-duyet'),
    path('nhan-vien/de-xuat-khong-phe-duyet/',Dexuathuy.as_view(),name='dexuat-huy'),
    path('nhan-vien/quan-ly-de-xuat/chua-duyet/',Quanlydexuat.as_view(),name='quan-ly-de-xuat'),
    path('nhan-vien/quan-ly-de-xuat/sep-chua-duyet/',Quanlydexuat_sepduyet.as_view(),name='quan-ly-de-xuat-sep'),
    path('nhan-vien/de-xuat/<int:dexuat_id>', Xulyduyet_tp.as_view(), name='xu-ly-duyet-tp'),
    path('nhan-vien/de-xuat/duyet-de-xuat/<int:dexuat_id>', Xulyduyet_sep.as_view(), name='xu-ly-duyet-sep'),
    path('nhan-vien/quan-ly-de-xuat/da-duyet/',Quanlydexuat_daduyet.as_view(),name='quan-ly-de-xuat-da-duyet'),
    path('nhan-vien/quan-ly-de-xuat/da-tam-ung/',Quanlydexuat_datamung.as_view(),name='quan-ly-de-xuat-da-tam-ung'),
    path('nhan-vien/quan-ly-de-xuat/da-giai-chi/',Quanlydexuat_dagiaichi.as_view(),name='quan-ly-de-xuat-da-giai-chi'),
    path('nhan-vien/quan-ly-de-xuat/da-huy/',Quanlydexuat_dahuy.as_view(),name='quan-ly-de-xuat-da-huy'),
    path('nhan-vien/de-xuat/xem-de-xuat/<int:dexuat_id>',View_dexuat.as_view(),name='view-dexuat'),
    path('nhan-vien/de-xuat/sua-de-xuat/<int:dexuat_id>',Editdexuat.as_view(),name='edit-dexuat'),

    path('nhan-vien/quan-ly-giai-chi/nhap-tam-ung/',Nhaptamung.as_view(),name='nhap-tam-ung'),
    path('nhan-vien/quan-ly-giai-chi/da-tam-ung/',Datamung.as_view(),name='da-tam-ung'),
    path('nhan-vien/quan-ly-giai-chi/form-da-tam-ung/<int:dexuat_id>',Formnhap_tamung.as_view(),name='form-nhap-tam-ung'),
    path('nhan-vien/quan-ly-giai-chi/form-dieu-chinh-tam-ung/<int:dexuat_id>',Formdieuchinh_tamung.as_view(),name='form-dieu-chinh-tam-ung'),
    path('nhan-vien/giai-chi/tao-giai-chi/',Taogiaichi.as_view(),name='tao-giai-chi'),
    path('nhan-vien/giai-chi/tao-giai-chi-tu-de-xuat/<int:dexuat_id>',Giaichi_dx.as_view(),name='tao-giai-chi-dx'),
    path('nhan-vien/quan-ly-giai-chi/tao-giai-chi-hang-hoa-moi/',Giaichihanghoa_moi.as_view(),name='tao-giai-chi-hang-hoa-moi'),
    path('nhan-vien/quan-ly-giai-chi/tao-giai-chi-khac-moi/',Giaichikhac_moi.as_view(),name='tao-giai-chi-khac-moi'),
    path('nhan-vien/quan-ly-giai-chi/tao-giai-chi-thiet-bi-moi/',Giaichithietbi_moi.as_view(),name='tao-giai-chi-thiet-bi-moi'),
    path('nhan-vien/quan-ly-giai-chi/giai-chi-chua-duyet/',Giaichichuaduyet.as_view(),name='giai-chi-chua-duyet'),
    path('nhan-vien/quan-ly-giai-chi/giai-chi-da-duyet/',Giaichidaduyet.as_view(),name='giai-chi-da-duyet'),
    path('nhan-vien/quan-ly-giai-chi/giai-chi-da-huy/',Giaichidahuy.as_view(),name='giai-chi-da-huy'),
    path('nhan-vien/quan-ly-giai-chi/giai-chi-da-thanh-toan/',Giaichidathanhtoan.as_view(),name='giai-chi-da-thanh-toan'),
    path('nhan-vien/giai-chi/view-giai-chi/<int:giaichi_id>',View_giaichi.as_view(),name='view-giai-chi'),
    path('nhan-vien/giai-chi/edit-giai-chi/<int:giaichi_id>',Edit_giaichi.as_view(),name='edit-giai-chi'),
    path('nhan-vien/giai-chi/view-giai-chi-tp/<int:giaichi_id>',View_giaichi_tp.as_view(),name='view-giai-chi-tp'),
    path('nhan-vien/giai-chi/bao-cao-giai-chi/',Baocaogiaichi.as_view(),name='bao-cao-giai-chi'),
    path('load-gia-chi/', Loadgiaichi.as_view(), name='load-giai-chi'),


    path('nhan-vien/quan-ly-giai-chi/',Quanlygiaichi.as_view(),name='quan-ly-giai-chi-tp'),
    path('nhan-vien/quan-ly-giai-chi-sep/',Quanlygiaichi_sep.as_view(),name='quan-ly-giai-chi-sep'),
    path('nhan-vien/quan-ly-giai-chi/ql-giai-chi-da-duyet',Quanlygiaichi_daduyet.as_view(),name='quan-ly-giaichi-da-duyet'),
    path('nhan-vien/quan-ly-giai-chi/ql-giai-chi-da-hoan-thanh',Quanlygiaichi_hoanthanh.as_view(),name='quan-ly-giaichi-da-hoan-thanh'),
    path('nhan-vien/quan-ly-giai-chi/ql-giai-chi-da-huy',Quanlygiaichi_dahuy.as_view(),name='quan-ly-giaichi-da-huy'),
    path('nhan-vien/quan-ly-giai-chi/xu-ly-giai-chi-tp/<int:giaichi_id>',Xu_ly_giai_chi.as_view(),name='xu-ly-giai-chi-tp'),
    path('nhan-vien/quan-ly-giai-chi/xu-ly-giai-chi-sep/<int:giaichi_id>',Xu_ly_giai_chi.as_view(),name='xu-ly-giai-chi-sep'),

    path('nhan-vien/nhap-khach-hang-lon/',Create_khl.as_view(),name="nhap-khach-hang-lon"),
    path('nhan-vien/danh-sach-khach-hang-lon/',Danhsach_khachhanglon.as_view(),name="danh-sach-khach-hang-lon"),
    path('nhan-vien/xem-sach-khach-hang-lon/<int:khachhang_id>',View_khachhanglon.as_view(),name="xem-khach-hang-lon"),
    path('nhan-vien/sua-sach-khach-hang-lon/<int:khachhang_id>',Edit_khachhanglon.as_view(),name="sua-khach-hang-lon"),

    path('nhan-vien/thu-quy/thanh-toan-giai-chi/',Thanhtoan_giaichi.as_view(),name="thanh-toan-giai-chi"),
    path('nhan-vien/thu-quy/thanh-toan-giai-chi/<int:giaichi_id>',Xacnhanthanhtoan_giaichi.as_view(),name="nhap-thanh-toan-giai-chi"),

    path('nhap-hang/',Nhaphangs.as_view(),name="nhap-hang"),
    path('sua-phieu-nhap-hang/<int:code_id>',Viewphieunhap.as_view(),name='view-nhap-hang'),
    path('phieu-nhap-kho/',Phieunhapkho.as_view(),name="phieu-nhap-kho"),
    path('load-courses/', load_courses.as_view(), name='ajax_load_courses'),
    path('quan-ly-nhap-hang',Quanlynhaphang.as_view(),name="quan-ly-nhap-hang"),
    path('nhap-hang-chua-duyet',Nhaphangchuaduyet.as_view(),name='nhaphangchuaduyet'),
    path('nhap-hang-chua-duyet-gap',Nhaphangchuaduyetgap.as_view(),name='nhaphangchuaduyetgap'),
    path('duyet-nhap-hang/<int:code_id>',Duyetnhaphang.as_view(),name='duyetnhaphang'),
    path('phieu-nhap-hang/da-duyet/',Nhaphangdaduyet.as_view(),name='nhaphangdapheduyet'),
    path('xuat-hang/',Xuathang.as_view(),name="xuat-hang"),
    path('ton-kho/',Tonkho.as_view(),name="ton-kho"),
    path('kho-van/thu-kho-can-xu-ly/',Thukho_Canxuly.as_view(),name="thu-kho-can-xu-ly"),
    path('kho-van/thu-kho-can-xu-ly/<int:code_id>',Formxulynhapkho.as_view(),name="form-thu-kho-can-xu-ly"),
    path('kho-van/thu-kho-treo/',Thukho_Treo.as_view(),name="thu-kho-treo"),
    path('dieu-chuyen-kho/',Dieuchuyenkho.as_view(),name="dieu-chuyen-kho"),
              ]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mergepdf/urls.py
from django.urls import path
from . import views

# namespace
app_name = 'pdf'

urlpatterns = [
    # Upload pdf, pages need to extract user input, return to the page to be extracted
    path('tach-trang/', views.pdf_extract, name='pdf_extract'),
]

mergepdf/models.py
from django.db import models

# Create your models here.

mergepdf/forms.py
from django import forms
from django.forms import widgets


class PdfUploadForm(forms.Form):
    file = forms.FileField(label="",widget=forms.FileInput(attrs={"class":"form-control"}))
    page = forms.IntegerField(min_value=1, label="Nhập Trang Cần lấy",widget=forms.NumberInput(attrs={"class":"form-control"}))
    
class Pdfmerge(forms.Form):
    file = forms.FileField(label=" Chọn File PDF để  Nối ",widget=forms.FileInput(attrs={"class":"form-control","multiple":"multiple"}))

mergepdf/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import *
import PyPDF2


# Create your views here.
def pdf_extract(request):
    
    if request.method == 'POST':
        if 'extractpdf' in request.POST:
            # If you submit via POST
            form = PdfUploadForm(request.POST, request.FILES)
            if form.is_valid():
                # Such as form validation, access to extract files page
                page_num = int(request.POST.get("page"))
                # Pdf document pages from the object code is zero, so minus 1
                page_index = page_num - 1
                # Get upload the file object
                f = request.FILES['file']
                
                # Open uploaded files, write new PDF file
                with open('original.pdf', 'wb+') as pdfFileObj:
                    for chunk in f.chunks():
                        pdfFileObj.write(chunk)

                                                               # Use PyPDF2 read the new PDF file
                        pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
                    
                                         # Use PyPDF2 extract Page Object
                        pageObj = pdfReader.getPage(page_index) 
                        print(pageObj)
                                                                # Use PyPDF2 create a new PDF file objects
                        pdfWriter = PyPDF2.PdfFileWriter()
                        # Add a page object that has been read
                        pdfWriter.addPage(pageObj)
                        # Write a new page will extract the PDF file
                        with open('extracted_pages.pdf', 'wb') as pdfOutputFile:
                            pdfWriter.write(pdfOutputFile)
                        # Open a new PDF file, output by HttpResponse
                        with open('extracted_pages.pdf', 'rb') as pdfExtract:
                            response = HttpResponse(pdfExtract.read(), content_type='application/pdf')
                            response['Content-Disposition'] = 'attachment; filename="extracted_page_{}.pdf"'.format(page_num)
                            return response
                    

        if 'mergepdf' in request.POST:
            return HttpResponse("Oh my chúi ")
            
    else:
                # If the user does not pass the POST, submitting to generate an empty form
                form = PdfUploadForm()
                form_merge =Pdfmerge()
                context = {
                    'form':form,
                    'form_merge':form_merge,
                }
                return render(request, 'mergepdf/pdf.html',context)
        

     

templates/mergepdf/pdf.html
{% extends 'base.html'%}
{%load static%}
{% block cssnhanvien %}
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css'%}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css'%}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css'%}">
{%endblock%}

{%block file-pdf%}

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col col-4">


                    <div class="card card-primary card-outline">
                        <div class="card-header">
                          <h3 class="card-title">
                            <i class="far fa-chart-bar"></i>
                            Tách 1 Trang Của File PDF
                          </h3>
          
                          <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                              <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove">
                              <i class="fas fa-times"></i>
                            </button>
                          </div>
                        </div>
                        <div class="card-body">
                          <div id="line-chart" style="height: 200px;">
                            <form method="post" enctype="multipart/form-data" action="">{% csrf_token %}
                                {{ form.as_p }}
                                <input type="submit" id="test_button" name="extractpdf" class="form-control btn btn-dark" value="Xuất File" />
                            </form>
                        
                        </div>
                        </div>
                        <!-- /.card-body-->
                    </div>


                </div>
                <!-- end col-->
                <!-- ? -->
               <script>
                 var input = document.getElementById("files");
                  var reader = new FileReader();
                  reader.readAsBinaryString(input.files[0]);
                  reader.onloadend = function(){
                      var count = reader.result.match(/\/Type[\s]*\/Page[^s]/g).length;
                      console.log('Number of Pages:',count );
                  }

               </script>
                <!--  -->
                <div class="col col-4">


                    <div class="card card-primary card-outline">
                        <div class="card-header">
                          <h3 class="card-title">
                            <i class="far fa-chart-bar"></i>
                            Gộp File PDF
                          </h3>
          
                          <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                              <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove">
                              <i class="fas fa-times"></i>
                            </button>
                          </div>
                        </div>
                        <div class="card-body">
                          <div id="line-chart" style="height: 200px;">
                            <form method="post" enctype="multipart/form-data" action="">{% csrf_token %}
                                {{ form_merge.as_p }}
                                <input type="submit" id="test_button1" name="mergepdf" class="form-control btn btn-info" value="Nối File" />
                            </form>
                        
                        </div>
                        </div>
                        <!-- /.card-body-->
                    </div>


                </div>
                <!-- end col-->

            </div>
            <!--end row -->
            
        </div>
    </section>
    

</div>




<script>



$(document).ready(function(){
$("#test_button").click(function() {
var test_value = $("#id_file").val();
var extension = test_value.split('.').pop().toLowerCase();
var page = $("#id_page").val();
if ($.inArray(extension, ['pdf',]) == -1) {
alert("File PDF không hợp lệ!");
return false;
} else {
alert("Bạn Đang Tách trang : " + page + " -File PDF -");
return true;
}
});
});
</script>

{% endblock%}