erp/urls.py
from django.contrib import admin
from django.urls import path,include
from qlns.views import *
from khovan.views import *
from khachhang.views import *
from django.conf import settings

from django.conf.urls.static import static

admin.site.index_title="Quản Trị Hệ Thống"
urlpatterns = [
    path('admin/', admin.site.urls,name="admin"),
    path('pdf/', include('mergepdf.urls')),
    path('report/',Report.as_view(),name='report'),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('', Index.as_view(),name='index'),
    path('login/', Login.as_view(),name='login'),
    path('logout',Logout.as_view(),name='logout'),
    path('api-auth/', include('rest_framework.urls')),
    path('giao-viec/', Giaoviec.as_view(),name='giaoviec'),
    path('nhanvien/', Nhanvientotal.as_view(), name='nhanvien'),
    path('get-nhan-vien/', Getnhanvien.as_view(),name='getnhanvien'),
    path('profile/',Profile.as_view(),name='profile'),
    path('dsnhanvien/',Dsnhanvien.as_view(),name='dsnhanvien'),
    path('viewnhanvien/', Viewnhanvien.as_view(), name='viewnhanvien'),
    path('deletenhanvien/',Delete_checkbox.as_view(), name='delete-nhanvien'),
    path('phieu-luong-upload/',Phieuluongupload.as_view(), name='phieuluongupload'),
    path('nhanvien/delete/<int:nhanvien_id>',Deletenhanvien.as_view(),name='deletenhanvien'),
    path('nhan-vien/xem-nhan-vien/<int:nhanvien_id>', Changenhanvien.as_view(), name='xemnhanvien'),
    path('phieu-luong/nhan-vien/<int:nhanvien_id>', Phieuluongcanhan.as_view(), name='xemphieuluong'),
    path('phieu-luong-user', Phieuluonguser.as_view(), name='xemphieuluonguser'),

    path('nhan-vien/tao-de-xuat/',Dexuats.as_view(),name='form-de-xuat'),
    path('nhan-vien/de-xuat-chua-duyet/',Dexuatchuaduyet.as_view(),name='dexuat-chua-duyet'),
    path('nhan-vien/de-xuat-da-duyet/',Dexuatdaduyet.as_view(),name='dexuat-da-duyet'),
    path('nhan-vien/de-xuat-khong-phe-duyet/',Dexuathuy.as_view(),name='dexuat-huy'),
    path('nhan-vien/quan-ly-de-xuat/chua-duyet/',Quanlydexuat.as_view(),name='quan-ly-de-xuat'),
    path('nhan-vien/quan-ly-de-xuat/sep-chua-duyet/',Quanlydexuat_sepduyet.as_view(),name='quan-ly-de-xuat-sep'),
    path('nhan-vien/de-xuat/<int:dexuat_id>', Xulyduyet_tp.as_view(), name='xu-ly-duyet-tp'),
    path('nhan-vien/de-xuat/duyet-de-xuat/<int:dexuat_id>', Xulyduyet_sep.as_view(), name='xu-ly-duyet-sep'),
    path('nhan-vien/quan-ly-de-xuat/da-duyet/',Quanlydexuat_daduyet.as_view(),name='quan-ly-de-xuat-da-duyet'),
    path('nhan-vien/quan-ly-de-xuat/da-tam-ung/',Quanlydexuat_datamung.as_view(),name='quan-ly-de-xuat-da-tam-ung'),
    path('nhan-vien/quan-ly-de-xuat/da-giai-chi/',Quanlydexuat_dagiaichi.as_view(),name='quan-ly-de-xuat-da-giai-chi'),
    path('nhan-vien/quan-ly-de-xuat/da-huy/',Quanlydexuat_dahuy.as_view(),name='quan-ly-de-xuat-da-huy'),
    path('nhan-vien/de-xuat/xem-de-xuat/<int:dexuat_id>',View_dexuat.as_view(),name='view-dexuat'),
    path('nhan-vien/de-xuat/sua-de-xuat/<int:dexuat_id>',Editdexuat.as_view(),name='edit-dexuat'),

    path('nhan-vien/quan-ly-giai-chi/nhap-tam-ung/',Nhaptamung.as_view(),name='nhap-tam-ung'),
    path('nhan-vien/quan-ly-giai-chi/da-tam-ung/',Datamung.as_view(),name='da-tam-ung'),
    path('nhan-vien/quan-ly-giai-chi/form-da-tam-ung/<int:dexuat_id>',Formnhap_tamung.as_view(),name='form-nhap-tam-ung'),
    path('nhan-vien/quan-ly-giai-chi/form-dieu-chinh-tam-ung/<int:dexuat_id>',Formdieuchinh_tamung.as_view(),name='form-dieu-chinh-tam-ung'),
    path('nhan-vien/giai-chi/tao-giai-chi/',Taogiaichi.as_view(),name='tao-giai-chi'),
    path('nhan-vien/giai-chi/tao-giai-chi-tu-de-xuat/<int:dexuat_id>',Giaichi_dx.as_view(),name='tao-giai-chi-dx'),
    path('nhan-vien/quan-ly-giai-chi/tao-giai-chi-hang-hoa-moi/',Giaichihanghoa_moi.as_view(),name='tao-giai-chi-hang-hoa-moi'),
    path('nhan-vien/quan-ly-giai-chi/tao-giai-chi-khac-moi/',Giaichikhac_moi.as_view(),name='tao-giai-chi-khac-moi'),
    path('nhan-vien/quan-ly-giai-chi/tao-giai-chi-thiet-bi-moi/',Giaichithietbi_moi.as_view(),name='tao-giai-chi-thiet-bi-moi'),
    path('nhan-vien/quan-ly-giai-chi/giai-chi-chua-duyet/',Giaichichuaduyet.as_view(),name='giai-chi-chua-duyet'),
    path('nhan-vien/quan-ly-giai-chi/giai-chi-da-duyet/',Giaichidaduyet.as_view(),name='giai-chi-da-duyet'),
    path('nhan-vien/quan-ly-giai-chi/giai-chi-da-huy/',Giaichidahuy.as_view(),name='giai-chi-da-huy'),
    path('nhan-vien/quan-ly-giai-chi/giai-chi-da-thanh-toan/',Giaichidathanhtoan.as_view(),name='giai-chi-da-thanh-toan'),
    path('nhan-vien/giai-chi/view-giai-chi/<int:giaichi_id>',View_giaichi.as_view(),name='view-giai-chi'),
    path('nhan-vien/giai-chi/edit-giai-chi/<int:giaichi_id>',Edit_giaichi.as_view(),name='edit-giai-chi'),
    path('nhan-vien/giai-chi/view-giai-chi-tp/<int:giaichi_id>',View_giaichi_tp.as_view(),name='view-giai-chi-tp'),
    path('nhan-vien/giai-chi/bao-cao-giai-chi/',Baocaogiaichi.as_view(),name='bao-cao-giai-chi'),
    path('load-gia-chi/', Loadgiaichi.as_view(), name='load-giai-chi'),


    path('nhan-vien/quan-ly-giai-chi/',Quanlygiaichi.as_view(),name='quan-ly-giai-chi-tp'),
    path('nhan-vien/quan-ly-giai-chi-sep/',Quanlygiaichi_sep.as_view(),name='quan-ly-giai-chi-sep'),
    path('nhan-vien/quan-ly-giai-chi/ql-giai-chi-da-duyet',Quanlygiaichi_daduyet.as_view(),name='quan-ly-giaichi-da-duyet'),
    path('nhan-vien/quan-ly-giai-chi/ql-giai-chi-da-hoan-thanh',Quanlygiaichi_hoanthanh.as_view(),name='quan-ly-giaichi-da-hoan-thanh'),
    path('nhan-vien/quan-ly-giai-chi/ql-giai-chi-da-huy',Quanlygiaichi_dahuy.as_view(),name='quan-ly-giaichi-da-huy'),
    path('nhan-vien/quan-ly-giai-chi/xu-ly-giai-chi-tp/<int:giaichi_id>',Xu_ly_giai_chi.as_view(),name='xu-ly-giai-chi-tp'),
    path('nhan-vien/quan-ly-giai-chi/xu-ly-giai-chi-sep/<int:giaichi_id>',Xu_ly_giai_chi.as_view(),name='xu-ly-giai-chi-sep'),

    path('nhan-vien/nhap-khach-hang-lon/',Create_khl.as_view(),name="nhap-khach-hang-lon"),
    path('nhan-vien/danh-sach-khach-hang-lon/',Danhsach_khachhanglon.as_view(),name="danh-sach-khach-hang-lon"),
    path('nhan-vien/xem-sach-khach-hang-lon/<int:khachhang_id>',View_khachhanglon.as_view(),name="xem-khach-hang-lon"),
    path('nhan-vien/sua-sach-khach-hang-lon/<int:khachhang_id>',Edit_khachhanglon.as_view(),name="sua-khach-hang-lon"),

    path('nhan-vien/thu-quy/thanh-toan-giai-chi/',Thanhtoan_giaichi.as_view(),name="thanh-toan-giai-chi"),
    path('nhan-vien/thu-quy/thanh-toan-giai-chi/<int:giaichi_id>',Xacnhanthanhtoan_giaichi.as_view(),name="nhap-thanh-toan-giai-chi"),

    path('nhap-hang/',Nhaphangs.as_view(),name="nhap-hang"),
    path('sua-phieu-nhap-hang/<int:code_id>',Viewphieunhap.as_view(),name='view-nhap-hang'),
    path('phieu-nhap-kho/',Phieunhapkho.as_view(),name="phieu-nhap-kho"),
    path('load-courses/', load_courses.as_view(), name='ajax_load_courses'),
    path('quan-ly-nhap-hang',Quanlynhaphang.as_view(),name="quan-ly-nhap-hang"),
    path('nhap-hang-chua-duyet',Nhaphangchuaduyet.as_view(),name='nhaphangchuaduyet'),
    path('nhap-hang-chua-duyet-gap',Nhaphangchuaduyetgap.as_view(),name='nhaphangchuaduyetgap'),
    path('duyet-nhap-hang/<int:code_id>',Duyetnhaphang.as_view(),name='duyetnhaphang'),
    path('phieu-nhap-hang/da-duyet/',Nhaphangdaduyet.as_view(),name='nhaphangdapheduyet'),
    path('xuat-hang/',Xuathang.as_view(),name="xuat-hang"),
    path('ton-kho/',Tonkho.as_view(),name="ton-kho"),
    path('kho-van/thu-kho-can-xu-ly/',Thukho_Canxuly.as_view(),name="thu-kho-can-xu-ly"),
    path('kho-van/thu-kho-can-xu-ly/<int:code_id>',Formxulynhapkho.as_view(),name="form-thu-kho-can-xu-ly"),
    path('kho-van/thu-kho-treo/',Thukho_Treo.as_view(),name="thu-kho-treo"),
    path('dieu-chuyen-kho/',Dieuchuyenkho.as_view(),name="dieu-chuyen-kho"),
              ]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

qlns/models.py

from django.contrib.auth import *
from django.db import models
from django.contrib import admin
from django.db.models.fields.related import OneToOneField
from django.utils.html import format_html
from django.contrib.auth.models import AbstractUser,User
from ckeditor.fields import *
from ckeditor_uploader.fields import *


class Phongban(models.Model):
    tenpb = models.CharField(default='',unique=True,max_length=255,verbose_name='Tên Phòng Ban')
    ngaythanhlap = models.DateTimeField(verbose_name='Năm thành lập',null=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)

    class Meta:
        verbose_name = "PHÒNG BAN"
        verbose_name_plural = 'PHÒNG BAN'

    def __str__(self):
        return self.tenpb

class Nhanvien(models.Model):
    manv = models.CharField(default='',unique=True,max_length=255,verbose_name='Mã Nhân Viên')
    username = models.OneToOneField(User,on_delete=models.CASCADE,verbose_name='Tài Khoản Nhân Viên')
    tennv = models.CharField(default='', max_length=255, verbose_name='Họ Tên Nhân Viên')
    gioitinh = models.BooleanField(default='',verbose_name='Check - Nếu là nam')
    ngaysinh =models.DateField(verbose_name='Ngày Sinh')
    diachi = models.CharField(default='', max_length=255, verbose_name='Địa chỉ thường trú')
    quequan =models.CharField(default='', max_length=255, verbose_name='Quê Quán')
    cmnd = models.CharField(default='', max_length=12, verbose_name='CCID')
    cmnd_1 =models.ImageField(default='',null=True, blank=True,upload_to='img/', verbose_name='Ảnh mặt trước CCID')
    cmnd_2 =models.ImageField(default='',null=True, blank=True, upload_to='img/', verbose_name='Ảnh mặt sau CCID')
    avatar = models.ImageField(default='',null=True, blank=True, upload_to='img/', verbose_name='Ảnh chân dung')
    sdt = models.CharField(default='', unique=True, max_length=255, verbose_name='Số Điện Thoại')
    line= models.CharField(default='', max_length=255, verbose_name='Line nội bộ')
    email =models.CharField(default='',unique=True, null=True,blank=True ,max_length=255, verbose_name='Email')
    phongban = models.ForeignKey(Phongban,default='',null=True,blank=True,on_delete=models.CASCADE)
    tinhtrangcongviec = models.BooleanField(default='1',verbose_name='Check --- (nếu nhân viên chính thức) ')
    chuky1 =models.FileField(blank=True,null=True,verbose_name='Upload chữ ký 1 ')
    chuky2 = models.FileField(blank=True, null=True, verbose_name='Upload chữ ký 2 ')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        verbose_name = "NHÂN VIÊN"
        verbose_name_plural = 'NHÂN VIÊN'


    def __str__(self):
        return self.tennv
class Chucvu_Congviec(models.Model):

    nhanvien = models.ForeignKey(Nhanvien ,on_delete=models.CASCADE,verbose_name='Nhân Viên')
    phongban = models.ForeignKey(Phongban,on_delete=models.CASCADE,verbose_name='Phòng ban')
    tencongviec = models.CharField(default='', max_length=255, verbose_name='Tên Công việc+ Chúc Vụ')
    motacongviec = models.TextField(verbose_name='Mô tả công việc')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name = "NHÂN VIÊN CHỨC VỤ"
        verbose_name_plural = 'NHÂN VIÊN CHỨC VỤ'

    def __int__(self):
        return self.nhanvien

class Baohiemyte(models.Model):
    nhanvien =models.OneToOneField(Nhanvien, on_delete=models.CASCADE)
    masobhyt = models.CharField(default='', unique=True, max_length=255, verbose_name='Mã Số BHXH')
    ngaythamgia = models.DateField(verbose_name='Ngày tham gia')
    noidangky = models.CharField(default='', max_length=255, verbose_name='Nơi đăng ký BHYT')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name = "BẢO HIỂM Y TẾ"
        verbose_name_plural = 'BẢO HIỂM Y TẾ'
    def __str__(self):
        return self.masobhyt

class Baohiemxahoi(models.Model):
    nhanvien = models.OneToOneField(Nhanvien, on_delete=models.CASCADE)
    masobhxh = models.CharField(unique=True,max_length=255,verbose_name='Mã Số BHXH')
    ngaythamgia =  models.DateField(verbose_name='Ngày tham gia')
    noidangky = models.CharField(default='', max_length=255, verbose_name='Địa chỉ đăng ký')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name = "BẢO HIỂM XÃ HỘI"
        verbose_name_plural = 'BẢO HIỂM XÃ HỘI'
    def __str__(self):
        return self.masobhxh

class Quatrinhdongbhxh(models.Model):
    tennhanvien = models.ForeignKey(Nhanvien,on_delete=models.CASCADE,verbose_name='Nhân Viên Đóng BHXH')
    thoigiandong = models.DateTimeField(verbose_name='Ngày-Tháng-Năm Đóng')
    sotiendong   = models.CharField(default='',max_length=255,verbose_name='Số Tiền Đóng BHXH')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name = "QUÁ TRÌNH ĐÓNG BẢO HIỂM XÃ HỘI"
        verbose_name_plural = "QUÁ TRÌNH ĐÓNG BẢO HIỂM XÃ HỘI"
    def __int__(self):
        return self.tennhanvien


class Hosonhanvien(models.Model):
    nhanvien = models.OneToOneField(Nhanvien, on_delete=models.CASCADE,verbose_name='Họ Tên Nhân Viên')
    masobh = models.CharField(unique=True,max_length=255,verbose_name='Mã Số HDLD ')
    ngaythuviec =  models.DateField(verbose_name='Ngày thử việc')
    ngaychinhthuc = models.DateField(verbose_name='Ngày làm chính thức')
    chuyenmon = models.CharField(default='', max_length=255, verbose_name='Chuyên ngành')
    vanhoa = models.CharField(default='', max_length=255, verbose_name='Trình độ')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "HỒ SƠ NHÂN VIÊN"
        verbose_name_plural = 'HỒ SƠ NHÂN VIÊN'
    def __int__(self):
        return self.nhanvien


class Loaihopdong(models.Model):
    maloaihd = models.CharField(default='', max_length=255, verbose_name='Tên Hợp Đồng')
    tenhd = models.CharField(default='', max_length=255,blank=True,null=True, verbose_name='Mô Tả Hợp Đồng')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name = "LOẠI HỢP ĐỒNG"
        verbose_name_plural = 'LOẠI HỢP ĐỒNG'

    def __str__(self):
        return self.maloaihd

class Quanlyhopdongkinhdoanh(models.Model):
    masohopdong = models.CharField(default='',unique=True, max_length=255, verbose_name='Mã Số Hợp Đồng')
    tenhopdong  = models.CharField(default='', max_length=255, verbose_name='Tên Hợp Đồng')
    khachhang = models.CharField(default='', max_length=255, verbose_name='Tên Khách Hàng')
    ngaytrinhky = models.DateField(default='', max_length=255, verbose_name='Ngày Trình Ký Hợp Đồng')
    filehopdong = models.FileField()
    loaihd  = models.ForeignKey(Loaihopdong,default='',on_delete=models.CASCADE, verbose_name='Loại Hợp Đồng')
    nhanvien = models.ForeignKey(Nhanvien,default='',on_delete=models.CASCADE, verbose_name='Nhân Viên phụ trách')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "QUẢN LÝ HỢP ĐỒNG CÔNG TY"
        verbose_name_plural = 'QUẢN LÝ HỢP ĐỒNG CÔNG TY'

    def __int__(self):
        return self.nhanvien


class Phieuluong_upload(models.Model):
    nhanvien = models.ForeignKey(Nhanvien,on_delete=models.CASCADE)
    thang = models.CharField(default='',null=True, blank=True, max_length=255)
    nam = models.CharField(default='',null=True, blank=True, max_length=255)
    ngaylamthucte = models.CharField(default='', null=True, blank=True,max_length=255)
    congchuan = models.CharField(default='', null=True, blank=True,max_length=255)
    congthembot = models.CharField(default='',null=True, blank=True, max_length=255)
    luongcoban = models.CharField(default='',null=True, blank=True, max_length=255)
    phucap = models.CharField(default='',null=True, blank=True, max_length=255)
    tiendienthoai = models.CharField(default='', null=True, blank=True,max_length=255)
    tienxang = models.CharField(default='', null=True, blank=True,max_length=255)
    tiencom = models.CharField(default='',null=True, blank=True, max_length=255)
    luongtrachnhiem = models.CharField(default='',null=True, blank=True, max_length=255)
    tiendienthoaihotro = models.CharField(default='',null=True, blank=True, max_length=255)
    ngaynghikhongpep = models.CharField(default='',null=True, blank=True, max_length=255)
    truluongnghikhongphep = models.CharField(default='', null=True, blank=True,max_length=255)
    hotrobaohiemtrongluong = models.CharField(default='', null=True, blank=True,max_length=255)
    luoncnx2 = models.CharField(default='', null=True, blank=True,max_length=255)
    tongthunhap = models.CharField(default='', null=True, blank=True,max_length=255)
    trutienunggiuathang = models.CharField(default='',null=True, blank=True, max_length=255)
    trutienmatunggiuathang = models.CharField(default='', null=True, blank=True,max_length=255)
    trutiendienthoaicongtytraho = models.CharField(default='',null=True, blank=True, max_length=255)
    trunotrongthang = models.CharField(default='',null=True, blank=True, max_length=255)
    trubaohiem = models.CharField(default='', null=True, blank=True,max_length=255)
    trutienphat = models.CharField(default='',null=True, blank=True, max_length=255)
    truluongluyke = models.CharField(default='', null=True, blank=True,max_length=255)

templates/khachhanglon/edit_khach_hang_lon.html
{% extends 'base.html'%}
{%load static%}

{%block form-khach_hang_lon%}

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">


 <div style="padding:50px">


        <h1>NHẬP KHÁCH HÀNG LỚN </h1><br>
        <form method="post" id="indexForm" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">

                <div class="col col-4">

                    <h6>
                        Tên Nhân Viên
                        <input type="text" value="{{khachhanglon.nhanvien}}"  readonly id="id_nhanvien" name="nhanvien" class="form-control">
                    </h6>

                    <h6>
                        Email
                        <input class="form-control " value="{{khachhanglon.email}}" disabled name="email" type="text"  >

                    </h6>
                    <h6>Phòng Ban :
                        <input type="text" value="{{khachhanglon.phongban}}" name="phongban" id="id_phongban" readonly class="form-control">

                   </h6>
                   <br>
                   <h6>
                       Tình Trạng Khách Hàng :
                       {% if khachhanglon.baogia == True %} 
                       
                       <select class="form-control" name = "tinhtrang">
                            <option value="0" selected>  Báo Giá  </option>
                            <option value="1">  Thương Thảo Hợp Đồng  </option> 
                            <option value="2">  Ký Hợp Đồng </option> 
                            <option value="3"> Hủy Theo </option>      
                        </select>
                       {%endif%}
                       {% if khachhanglon.thuongthaohopdong == True %}
                       <select class="form-control" name = "tinhtrang">
                                <option value="0" >  Báo Giá  </option>
                                <option value="1" selected>  Thương Thảo Hợp Đồng  </option> 
                                <option value="2">  Ký Hợp Đồng </option>
                                <option value="3"> Hủy Theo </option>       
                        </select>
                    {%endif%}
                       {% if khachhanglon.kyhopdong == True %} 
                       <select class="form-control" name = "tinhtrang">
                            <option value="0" >  Báo Giá  </option>
                            <option value="1" >  Thương Thảo Hợp Đồng  </option> 
                            <option value="2" selected>  Ký Hợp Đồng </option> 
                            <option value="3"> Hủy Theo </option>      
                       </select> 
                      {%endif%}
                      
                   </h6>
                   
                </div>
                <div class="col col-8">
                    <h6>Tên Khách Hàng :
                        <input type="text" value="{{khachhanglon.tenkhachhang}}" name="tenkhachhang" id="id_tenkhachhang"  required class="form-control">
                    </h6>
                    <h6>Địa Chỉ Khách Hàng:
                         <input type="text" value="{{khachhanglon.diachikh}}" name="diachikh" id="id_diachikh" required class="form-control">

                    </h6>
                    
                    <h6>Hạng Mục:
                        {{form.hangmuc}}   
                        
                    </h6>
                    
                    
                    
                    
                </div>
               
               
                <div class="col col-12 ">
                    
                    <h6>Tên Công Trình :</h6>
                    
                    <textarea name="tencongtrinh" id="id_tencongtrinh" class="form-control" placeholder="Nhập Tên Công Trình" required rows="1" >{{khachhanglon.diachicongtrinh}}</textarea>
                    
                    
                    <h6>Địa Chỉ Công Trình :</h6>
                    <textarea name="diachicongtrinh" id="id_diachicongtrinh" class="form-control" placeholder="Nhập Địa Chỉ Công Trình" required rows="1" >{{khachhanglon.tencongtrinh}}</textarea>
                    
                    <div>
                        <h6>Nội Dung Chi Tiết    :</h6>
                        {{form.noidung}}
                    </div>
                </div>
            </div>
            
            <br>
            <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; position: absolute;
            left: 50%;margin-left: -60px;">
               {%if khachhanglon.username == request.user %}
                <button type="submit" class="btn btn-bg btn-success">Cập Nhật</button>
               {%endif%}
                <a href="javascript:history.back()" class="btn btn-dark"> Quay Lại </a>
           
            </div>
                

            </div>





        </form>
</div>
</section>
</div>
</div>

<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

{%endblock%}