erp/urls.py
from django.contrib import admin
from django.urls import path,include
from qlns.views import *
from khovan.views import *
from khachhang.views import *
from django.conf import settings

from django.conf.urls.static import static

admin.site.index_title="Quản Trị Hệ Thống"
urlpatterns = [
    path('admin/', admin.site.urls,name="admin"),
    path('pdf/', include('mergepdf.urls')),
    path('report/',Report.as_view(),name='report'),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('', Index.as_view(),name='index'),
    path('login/', Login.as_view(),name='login'),
    path('logout',Logout.as_view(),name='logout'),
    path('api-auth/', include('rest_framework.urls')),
    path('giao-viec/', Giaoviec.as_view(),name='giaoviec'),
    path('nhanvien/', Nhanvientotal.as_view(), name='nhanvien'),
    path('get-nhan-vien/', Getnhanvien.as_view(),name='getnhanvien'),
    path('profile/',Profile.as_view(),name='profile'),
    path('dsnhanvien/',Dsnhanvien.as_view(),name='dsnhanvien'),
    path('viewnhanvien/', Viewnhanvien.as_view(), name='viewnhanvien'),
    path('deletenhanvien/',Delete_checkbox.as_view(), name='delete-nhanvien'),
    path('phieu-luong-upload/',Phieuluongupload.as_view(), name='phieuluongupload'),
    path('nhanvien/delete/<int:nhanvien_id>',Deletenhanvien.as_view(),name='deletenhanvien'),
    path('nhan-vien/xem-nhan-vien/<int:nhanvien_id>', Changenhanvien.as_view(), name='xemnhanvien'),
    path('phieu-luong/nhan-vien/<int:nhanvien_id>', Phieuluongcanhan.as_view(), name='xemphieuluong'),
    path('phieu-luong-user', Phieuluonguser.as_view(), name='xemphieuluonguser'),

    path('nhan-vien/tao-de-xuat/',Dexuats.as_view(),name='form-de-xuat'),
    path('nhan-vien/de-xuat-chua-duyet/',Dexuatchuaduyet.as_view(),name='dexuat-chua-duyet'),
    path('nhan-vien/de-xuat-da-duyet/',Dexuatdaduyet.as_view(),name='dexuat-da-duyet'),
    path('nhan-vien/de-xuat-khong-phe-duyet/',Dexuathuy.as_view(),name='dexuat-huy'),
    path('nhan-vien/quan-ly-de-xuat/chua-duyet/',Quanlydexuat.as_view(),name='quan-ly-de-xuat'),
    path('nhan-vien/quan-ly-de-xuat/sep-chua-duyet/',Quanlydexuat_sepduyet.as_view(),name='quan-ly-de-xuat-sep'),
    path('nhan-vien/de-xuat/<int:dexuat_id>', Xulyduyet_tp.as_view(), name='xu-ly-duyet-tp'),
    path('nhan-vien/de-xuat/duyet-de-xuat/<int:dexuat_id>', Xulyduyet_sep.as_view(), name='xu-ly-duyet-sep'),
    path('nhan-vien/quan-ly-de-xuat/da-duyet/',Quanlydexuat_daduyet.as_view(),name='quan-ly-de-xuat-da-duyet'),
    path('nhan-vien/quan-ly-de-xuat/da-tam-ung/',Quanlydexuat_datamung.as_view(),name='quan-ly-de-xuat-da-tam-ung'),
    path('nhan-vien/quan-ly-de-xuat/da-giai-chi/',Quanlydexuat_dagiaichi.as_view(),name='quan-ly-de-xuat-da-giai-chi'),
    path('nhan-vien/quan-ly-de-xuat/da-huy/',Quanlydexuat_dahuy.as_view(),name='quan-ly-de-xuat-da-huy'),
    path('nhan-vien/de-xuat/xem-de-xuat/<int:dexuat_id>',View_dexuat.as_view(),name='view-dexuat'),
    path('nhan-vien/de-xuat/sua-de-xuat/<int:dexuat_id>',Editdexuat.as_view(),name='edit-dexuat'),

    path('nhan-vien/quan-ly-giai-chi/nhap-tam-ung/',Nhaptamung.as_view(),name='nhap-tam-ung'),
    path('nhan-vien/quan-ly-giai-chi/da-tam-ung/',Datamung.as_view(),name='da-tam-ung'),
    path('nhan-vien/quan-ly-giai-chi/form-da-tam-ung/<int:dexuat_id>',Formnhap_tamung.as_view(),name='form-nhap-tam-ung'),
    path('nhan-vien/quan-ly-giai-chi/form-dieu-chinh-tam-ung/<int:dexuat_id>',Formdieuchinh_tamung.as_view(),name='form-dieu-chinh-tam-ung'),
    path('nhan-vien/giai-chi/tao-giai-chi/',Taogiaichi.as_view(),name='tao-giai-chi'),
    path('nhan-vien/giai-chi/tao-giai-chi-tu-de-xuat/<int:dexuat_id>',Giaichi_dx.as_view(),name='tao-giai-chi-dx'),
    path('nhan-vien/quan-ly-giai-chi/tao-giai-chi-hang-hoa-moi/',Giaichihanghoa_moi.as_view(),name='tao-giai-chi-hang-hoa-moi'),
    path('nhan-vien/quan-ly-giai-chi/tao-giai-chi-khac-moi/',Giaichikhac_moi.as_view(),name='tao-giai-chi-khac-moi'),
    path('nhan-vien/quan-ly-giai-chi/tao-giai-chi-thiet-bi-moi/',Giaichithietbi_moi.as_view(),name='tao-giai-chi-thiet-bi-moi'),
    path('nhan-vien/quan-ly-giai-chi/giai-chi-chua-duyet/',Giaichichuaduyet.as_view(),name='giai-chi-chua-duyet'),
    path('nhan-vien/quan-ly-giai-chi/giai-chi-da-duyet/',Giaichidaduyet.as_view(),name='giai-chi-da-duyet'),
    path('nhan-vien/quan-ly-giai-chi/giai-chi-da-huy/',Giaichidahuy.as_view(),name='giai-chi-da-huy'),
    path('nhan-vien/quan-ly-giai-chi/giai-chi-da-thanh-toan/',Giaichidathanhtoan.as_view(),name='giai-chi-da-thanh-toan'),
    path('nhan-vien/giai-chi/view-giai-chi/<int:giaichi_id>',View_giaichi.as_view(),name='view-giai-chi'),
    path('nhan-vien/giai-chi/edit-giai-chi/<int:giaichi_id>',Edit_giaichi.as_view(),name='edit-giai-chi'),
    path('nhan-vien/giai-chi/view-giai-chi-tp/<int:giaichi_id>',View_giaichi_tp.as_view(),name='view-giai-chi-tp'),
    path('nhan-vien/giai-chi/bao-cao-giai-chi/',Baocaogiaichi.as_view(),name='bao-cao-giai-chi'),
    path('load-gia-chi/', Loadgiaichi.as_view(), name='load-giai-chi'),


    path('nhan-vien/quan-ly-giai-chi/',Quanlygiaichi.as_view(),name='quan-ly-giai-chi-tp'),
    path('nhan-vien/quan-ly-giai-chi-sep/',Quanlygiaichi_sep.as_view(),name='quan-ly-giai-chi-sep'),
    path('nhan-vien/quan-ly-giai-chi/ql-giai-chi-da-duyet',Quanlygiaichi_daduyet.as_view(),name='quan-ly-giaichi-da-duyet'),
    path('nhan-vien/quan-ly-giai-chi/ql-giai-chi-da-hoan-thanh',Quanlygiaichi_hoanthanh.as_view(),name='quan-ly-giaichi-da-hoan-thanh'),
    path('nhan-vien/quan-ly-giai-chi/ql-giai-chi-da-huy',Quanlygiaichi_dahuy.as_view(),name='quan-ly-giaichi-da-huy'),
    path('nhan-vien/quan-ly-giai-chi/xu-ly-giai-chi-tp/<int:giaichi_id>',Xu_ly_giai_chi.as_view(),name='xu-ly-giai-chi-tp'),
    path('nhan-vien/quan-ly-giai-chi/xu-ly-giai-chi-sep/<int:giaichi_id>',Xu_ly_giai_chi.as_view(),name='xu-ly-giai-chi-sep'),

    path('nhan-vien/nhap-khach-hang-lon/',Create_khl.as_view(),name="nhap-khach-hang-lon"),
    path('nhan-vien/danh-sach-khach-hang-lon/',Danhsach_khachhanglon.as_view(),name="danh-sach-khach-hang-lon"),
    path('nhan-vien/xem-sach-khach-hang-lon/<int:khachhang_id>',View_khachhanglon.as_view(),name="xem-khach-hang-lon"),
    path('nhan-vien/sua-sach-khach-hang-lon/<int:khachhang_id>',Edit_khachhanglon.as_view(),name="sua-khach-hang-lon"),

    path('nhan-vien/thu-quy/thanh-toan-giai-chi/',Thanhtoan_giaichi.as_view(),name="thanh-toan-giai-chi"),
    path('nhan-vien/thu-quy/thanh-toan-giai-chi/<int:giaichi_id>',Xacnhanthanhtoan_giaichi.as_view(),name="nhap-thanh-toan-giai-chi"),

    path('nhap-hang/',Nhaphangs.as_view(),name="nhap-hang"),
    path('sua-phieu-nhap-hang/<int:code_id>',Viewphieunhap.as_view(),name='view-nhap-hang'),
    path('phieu-nhap-kho/',Phieunhapkho.as_view(),name="phieu-nhap-kho"),
    path('load-courses/', load_courses.as_view(), name='ajax_load_courses'),
    path('quan-ly-nhap-hang',Quanlynhaphang.as_view(),name="quan-ly-nhap-hang"),
    path('nhap-hang-chua-duyet',Nhaphangchuaduyet.as_view(),name='nhaphangchuaduyet'),
    path('nhap-hang-chua-duyet-gap',Nhaphangchuaduyetgap.as_view(),name='nhaphangchuaduyetgap'),
    path('duyet-nhap-hang/<int:code_id>',Duyetnhaphang.as_view(),name='duyetnhaphang'),
    path('phieu-nhap-hang/da-duyet/',Nhaphangdaduyet.as_view(),name='nhaphangdapheduyet'),
    path('xuat-hang/',Xuathang.as_view(),name="xuat-hang"),
    path('ton-kho/',Tonkho.as_view(),name="ton-kho"),
    path('kho-van/thu-kho-can-xu-ly/',Thukho_Canxuly.as_view(),name="thu-kho-can-xu-ly"),
    path('kho-van/thu-kho-can-xu-ly/<int:code_id>',Formxulynhapkho.as_view(),name="form-thu-kho-can-xu-ly"),
    path('kho-van/thu-kho-treo/',Thukho_Treo.as_view(),name="thu-kho-treo"),
    path('dieu-chuyen-kho/',Dieuchuyenkho.as_view(),name="dieu-chuyen-kho"),
              ]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

khovan/models.py
import time

from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.utils.html import format_html
from django.contrib.auth.models import AbstractUser,User
from qlns.models import *
from django.utils.timezone import now
# Create your models here.


class Gas(models.Model):
    tengas = models.CharField(default='',max_length=100,blank=False,null=False,verbose_name='Loại Gas')
    mota = models.CharField(max_length=500,blank=True,null=True,verbose_name='Mô tả (có thể bỏ trống)')
    class Meta:
        verbose_name = "LOẠI GAS"
        verbose_name_plural = 'LOẠI GAS'

    def __str__(self):
        return self.tengas
class Loaimay(models.Model):
    tenloai = models.CharField(default='',max_length=100,blank=False,null=False,verbose_name='Loại Máy')
    mota = models.CharField(max_length=500,blank=True,null=True,verbose_name='Mô tả (có thể bỏ trống)')
    class Meta:
        verbose_name = "LOẠI MÁY "
        verbose_name_plural = 'LOẠI MÁY '

    def __str__(self):
        return self.tenloai

class Congsuat(models.Model):
    tencongsuat = models.CharField(default='',max_length=100,blank=False,null=False,verbose_name=' Công suất ')
    mota = models.CharField(max_length=500,blank=True,null=True,verbose_name='Mô tả (có thể bỏ trống)')
    class Meta:
        verbose_name = "CÔNG SUẤT "
        verbose_name_plural = 'CÔNG SUẤT '

    def __str__(self):
        return self.tencongsuat

class Hemay(models.Model):
    tenhemay = models.CharField(default='',max_length=100,blank=False,null=False,verbose_name=' Hệ Máy ')
    mota = models.CharField(max_length=500,blank=True,null=True,verbose_name='Mô tả (có thể bỏ trống)')
    class Meta:
        verbose_name = "HỆ MÁY"
        verbose_name_plural = 'HỆ MÁY'

    def __str__(self):
        return self.tenhemay

class Nganhhang(models.Model):
    tennghanhhang = models.CharField(default='',max_length=100,blank=False,null=False,verbose_name='Tên Nghành Hàng ')
    mota = models.CharField(max_length=500,blank=True,null=True,verbose_name='Mô tả (có thể bỏ trống)')
    class Meta:
        verbose_name = "NGÀNH HÀNG "
        verbose_name_plural = 'NGÀNH HÀNG '

    def __str__(self):
        return self.tennghanhhang
class Hangsx(models.Model):
    tenhangsx = models.CharField(default='',max_length=100,blank=False,null=False,verbose_name='Tên Hãng ')
    mota = models.CharField(max_length=500,blank=True,null=True,verbose_name='Mô tả (có thể bỏ trống)')
    class Meta:
        verbose_name = "HÃNG SX "
        verbose_name_plural = 'HÃNG SX '

    def __str__(self):
        return self.tenhangsx


class Hanghoa(models.Model):
    code = models.IntegerField(default=0,unique=True)
    tenhanghoa = models.CharField(default='',max_length=100,blank=False,null=False,verbose_name='Tên Hàng Hoá (Dàn Lạnh/ Dàn Nóng.)')
    hangsx = models.ForeignKey(Hangsx,on_delete=models.CASCADE,verbose_name='Hãng Sản Xuất')
    nganhhang = models.ForeignKey(Nganhhang,on_delete=models.CASCADE,verbose_name='Danh Mục')
    hemay = models.ForeignKey(Hemay,on_delete=models.CASCADE,verbose_name='Hệ Máy ')
    congsuat = models.ForeignKey(Congsuat,on_delete=models.CASCADE,verbose_name='Công Suất')
    loaimay =  models.ForeignKey(Loaimay,on_delete=models.CASCADE,verbose_name='Loại Máy ')
    gas = models.ForeignKey(Gas,on_delete=models.CASCADE,verbose_name='Loại Gas ')
    giavon = models.IntegerField(default='0',blank=True,null=True,verbose_name='Giá Vốn ')
    mota = models.CharField(max_length=500,blank=True,null=True,verbose_name='Mô tả (có thể bỏ trống)')
    class Meta:
        verbose_name = "HÀNG HOÁ "
        verbose_name_plural = 'HÀNG HOÁ'

    def __str__(self):
        return self.tenhanghoa

class Khohang(models.Model):
    tenkho = models.CharField(max_length=200,blank=False,null=False,verbose_name='Tên Kho')
    diachi = models.CharField(max_length=500,blank=True,null=True,verbose_name='Địa Chỉ')
    class Meta:
        verbose_name = "KHO HÀNG "
        verbose_name_plural = 'KHO HÀNG'

    def __str__(self):
        return self.tenkho

class Thukho_Khohang(models.Model):
    nhanvien = models.ForeignKey(Nhanvien,on_delete=models.CASCADE)
    kho = models.ForeignKey(Khohang,on_delete=models.CASCADE)
    class Meta:
        verbose_name = "THỦ KHO"
        verbose_name_plural = 'THỦ KHO'

    def __str__(self):
        return self.nhanvien

class Nhaphang(models.Model):
    hanghoa = models.ForeignKey(Hanghoa, on_delete=models.CASCADE,verbose_name='Tên Hàng Hoá')
    soluong = models.IntegerField(default=0,blank=True,verbose_name='Số Lượng')
    kho = models.ForeignKey(Khohang,on_delete=models.CASCADE)
    tinhtrang = models.BooleanField(verbose_name='Tình Trạng -( Check Nếu Hàng Đã Thực Nhập )')

    class Meta:
        verbose_name = "NHẬP HÀNG "
        verbose_name_plural = 'NHẬP HÀNG'

    def __str__(self):
        return self.hanghoa


class Nhacungcap(models.Model):
    tennhacungcap =  models.CharField(max_length=200,blank=False,null=False,verbose_name='Tên Nhà Cung Cấp')
    diachinhacungcap =  models.CharField(max_length=200,blank=False,null=False,verbose_name='Địa chỉ nhà cung cấp')
    diachikhonhacungcap = models.CharField(max_length=200,blank=False,null=False,verbose_name='Địa chỉ nhà cung cấp')
    nhanvienquanly = models.ForeignKey(Nhanvien ,on_delete=models.CASCADE, verbose_name='Tên Nhân Viên Quản Lý')
    hanmuccongno = models.FloatField(default=0, blank=True,null=True,verbose_name='Hạn mức ')

    def __str__(self):
        return self.tennhacungcap

    class Meta:
        verbose_name = "NHÀ CUNG CẤP "
        verbose_name_plural = 'NHÀ CUNG CẤP'


class Phieunhaphang(models.Model):

    code  =  models.CharField(max_length=200,blank=False,null=False,verbose_name='Barcode',unique=True)
    nhacungcap  =  models.ForeignKey(Nhacungcap, on_delete = models.CASCADE, verbose_name='Nhà cung cấp' )
    noidung = models.JSONField(blank=False,null = False,verbose_name='Nội Dung ')
    username = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Tài Khoản')
    nhanvien =  models.CharField(max_length=200,blank=True,null=True,verbose_name='Tên Kinh doanh(không  điền trường này)')
    kho = models.ForeignKey(Khohang, on_delete=models.CASCADE, verbose_name='Kho')
        
    guiduyet= models.CharField(max_length=20, choices=[('1','Gui Ke Toan'),('0','Khong can gui duyet')], verbose_name='Trang Thai Duyệt')
    tinhtrang = models.BooleanField(verbose_name='Trang Thai Duyệt')
    tuchoi  =  models.BooleanField(verbose_name='Từ Chối')
    xulykho =  models.BooleanField(verbose_name="Xu Ly Kho")  
    thoigiantao = models.DateField()
    thoigiannhanhang = models.DateField()
    ghichu = models.CharField(default=".",max_length=200,blank=False,null=False,verbose_name='Ghi Chú  ')
    phanhoi =  models.CharField(default=".",max_length=200,blank=False,null=False,verbose_name='Phản Hồi  ')


    class Meta:
        verbose_name = "PHIẾU NHẬP XUẤT HÀNG "
        verbose_name_plural = 'PHIẾU NHẬP XUẤT HÀNG'

    def __str__(self):
        return self.code

class Nhapkho(models.Model):
    code = models.ForeignKey(Phieunhaphang, on_delete=models.CASCADE,verbose_name='Số Phiếu Nhập Hàng')
    noidung = models.JSONField()
    tinhtrang_hoanthanh = models.BooleanField( verbose_name='Tình Trạng Hoàn Thành 100% ')
    tinhtrang_treo = models.BooleanField( verbose_name='Tình Trạng Hoàn Thành < 100% ')
    thoigiantao = models.DateField(auto_now_add=True, blank=True) 
    
    class Meta:
        verbose_name = "NHẬP KHO "
        verbose_name_plural = 'NHẬP KHO'

    def __int__(self):
        return self.code

class Xuathang(models.Model):

    hanghoa = models.ForeignKey(Hanghoa, on_delete=models.CASCADE, verbose_name='Tên Hàng Hoá')
    soluong = models.IntegerField(default=0, verbose_name='Số Lượng')
    kho = models.ForeignKey(Khohang, on_delete=models.CASCADE, verbose_name='Tên Kho')

    tinhtrang = models.BooleanField(verbose_name='Tình Trạng -(Check Nếu Hàng Đã Thực Xuất)')

    class Meta:
        verbose_name = "XUẤT HÀNG "
        verbose_name_plural = 'XUẤT HÀNG'

    def __str__(self):
        return self.hanghoa



class Ton_kho(models.Model):
    hanghoa = models.ForeignKey(Hanghoa, on_delete=models.CASCADE, verbose_name='Tên Hàng Hoá')
    soluongnhap = models.IntegerField(default=0, verbose_name='Số Lượng Nhập')
    soluongxuat = models.IntegerField(default=0, verbose_name='Số Lượng Xuất')
    kho = models.ForeignKey(Khohang, on_delete=models.CASCADE, verbose_name='Tên Kho')

    def __int__(self):
        return self.hanghoa

    class Meta:
        verbose_name = "TỒN KHO "
        verbose_name_plural = 'TỒN KHO'

templates/duyetnhaphang.html
{% extends 'base.html'%}
{%load static%}

{%block duyetnhaphang%}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">

                        <li class="breadcrumb-item active">
                          
                      </li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title badge badge-pill badge-info">
                              DUYỆT NHẬP HÀNG
                            </h3>
                        </div>
                        <!-- /.card-header -->

                        <!-- /.card-body -->
                        
                        <div style="padding:30px;">
                        <form action=" " method="POST" class="form-horizontal" role="form">
                                {% csrf_token %}                   
                               <div><label>Nhân viên khinh danh  :</label> {{phieunhaphang.nhanvien}}</div>
                               <div><label>Ngầy Tạo   :</label> {{phieunhaphang.thoigiantao}}</div>
                               <div><label>Ngày Giao Dự Kiến  :</label> {{phieunhaphang.thoigiannhanhang}}</div>
                               <div><label>Kho   :</label> {{phieunhaphang.kho}}</div>
                               <div><label>Ghi Chú Kinh Doanh   :</label> {{phieunhaphang.ghichu}}</div>
                               <div>
                                   <table class="table table-hover table-bordered">
                                       <thead>
                                           <tr>
                                               
                                               <th>Tên Sản Phẩm</th>
                                               <th>Số Lượng</th>
                                               <th>Đơn Giá</th>
                                               <th>Thành Tiền</th>
                                           </tr>
                                       </thead>
                                       <tbody>
                                           <tr>
                                               <td>{{phieunhaphang.noidung.tenhang_1}}</td>
                                               <td>{{phieunhaphang.noidung.soluong_1}}</td>
                                               <td>{{phieunhaphang.noidung.dongia_1}}</td>
                                               <td></td>
                                           </tr>
                                           {% if phieunhaphang.noidung.tenhang_2  %}
                                           <tr>
                                               <td>{{phieunhaphang.noidung.tenhang_2}}</td>
                                               <td>{{phieunhaphang.noidung.soluong_2}}</td>
                                               <td>{{phieunhaphang.noidung.dongia_2}}</td>
                                               <td></td>
                                           </tr>
                                           {%endif%}
                                           {% if phieunhaphang.noidung.tenhang_3  %}
                                           <tr>
                                               <td>{{phieunhaphang.noidung.tenhang_3}}</td>
                                               <td>{{phieunhaphang.noidung.soluong_3}}</td>
                                               <td>{{phieunhaphang.noidung.dongia_3}}</td>
                                               <td></td>
                                           </tr>
                                           {%endif%}
                                           {% if phieunhaphang.noidung.tenhang_4  %}
                                           <tr>
                                               <td>{{phieunhaphang.noidung.tenhang_4}}</td>
                                               <td>{{phieunhaphang.noidung.soluong_4}}</td>
                                               <td>{{phieunhaphang.noidung.dongia_4}}</td>
                                               <td></td>
                                           </tr>
                                           {%endif%}
                                       </tbody>
                                   </table>
                               </div>
                              
                               <div><label>Phản Hồi Cho Kinh Danh   :</label>{{form.phanhoi}}<br>
                               
                                   <div class="radio">
                                       <label style="color:green;" id='nonhiden'>
                                         {{form.tinhtrang}}
                                           Duyệt Đơn Hàng
                                       </label>
                                       <br>
                                       <label style="color:red; " id='hiden'>
                                            {{form.tuchoi}}
                                           Từ Chối Đơn Hàng
                                       </label>
                                   </div>
                                   <br>

                                <div class="form-group">

                                    <div class="col-sm-10 col-sm-offset-2"><br>
                                      <button type="button" id="load" class="btn btn btn-lg btn-default">Refresh</button>
                                        <button type="submit" class="btn btn-lg btn-primary">Save</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        </div>
                    </div>
                    <!-- /.card -->

                   
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->




</div>

<script>
    $(document).ready(function(){
        $("#id_tinhtrang").change('checked',function(){
          $('#hiden').hide();
        });
    
          $("#id_tuchoi").change('checked',function(){
           
          $('#nonhiden').hide();
          $('#id_tinhtrang').not(this).prop('checked',this.checked);
        });

           $('#load').click(function() {
         location.reload();
           });

    });

    
</script>
{%endblock%}

templates/load_hanghoa.html
{% for course in courses %}<option value="{{ course.pk }}">{{ course.tenhanghoa }}</option>{% endfor %}{% for course in courses2 %}<option value="{{ course.pk }}">{{ course.tenhanghoa }}</option>{% endfor %}{% for course in courses3 %}<option value="{{ course.pk }}">{{ course.tenhanghoa }}</option>{% endfor %}{% for course in courses4 %}<option value="{{ course.pk }}">{{ course.tenhanghoa }}</option>{% endfor %}{% for item in nhanvien %}<option value="{{ item.pk }}">{{ item.sdt }}</option>{% endfor %}

templates/xuathang.html
{% extends 'base.html'%}{%load static%}{%block xuathang%}{%endblock%}